package com.francotte.homecontroller.core.designsystem.theme

import androidx.compose.ui.graphics.Color

// ---- Rouille & Pétrole — Clair ----
val primaryLight = Color(0xFF9A431D)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFDBCC)
val onPrimaryContainerLight = Color(0xFF370E00)
val secondaryLight = Color(0xFF785849)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFDBCC)
val onSecondaryContainerLight = Color(0xFF2C160C)
val tertiaryLight = Color(0xFF1F5E63)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFA6EAEF)
val onTertiaryContainerLight = Color(0xFF00201F)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFF8F5)
val onBackgroundLight = Color(0xFF23180F)
val surfaceLight = Color(0xFFFFF8F5)
val onSurfaceLight = Color(0xFF23180F)
val surfaceVariantLight = Color(0xFFF3DED4)
val onSurfaceVariantLight = Color(0xFF53433A)
val outlineLight = Color(0xFF85736A)
val outlineVariantLight = Color(0xFFD7C2B8)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF382E28)
val inverseOnSurfaceLight = Color(0xFFFEEDE5)
val inversePrimaryLight = Color(0xFFFFB59A)
val surfaceDimLight = Color(0xFFE6D6CD)
val surfaceBrightLight = Color(0xFFFFF8F5)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFDF1EB)
val surfaceContainerLight = Color(0xFFF8EBE4)
val surfaceContainerHighLight = Color(0xFFF2E5DE)
val surfaceContainerHighestLight = Color(0xFFECE0D9)

// ---- Rouille & Pétrole — Sombre ----
val primaryDark = Color(0xFFFFB59A)
val onPrimaryDark = Color(0xFF561D00)
val primaryContainerDark = Color(0xFF7A3211)
val onPrimaryContainerDark = Color(0xFFFFDBCC)
val secondaryDark = Color(0xFFE7BEAD)
val onSecondaryDark = Color(0xFF442A1F)
val secondaryContainerDark = Color(0xFF5D4033)
val onSecondaryContainerDark = Color(0xFFFFDBCC)
val tertiaryDark = Color(0xFF82D3D9)
val onTertiaryDark = Color(0xFF00363A)
val tertiaryContainerDark = Color(0xFF004F53)
val onTertiaryContainerDark = Color(0xFFA6EAEF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF191108)
val onBackgroundDark = Color(0xFFF0DFD4)
val surfaceDark = Color(0xFF191108)
val onSurfaceDark = Color(0xFFF0DFD4)
val surfaceVariantDark = Color(0xFF52443A)
val onSurfaceVariantDark = Color(0xFFD7C3B6)
val outlineDark = Color(0xFFA08D82)
val outlineVariantDark = Color(0xFF52443A)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFF0DFD4)
val inverseOnSurfaceDark = Color(0xFF382E28)
val inversePrimaryDark = Color(0xFF9A431D)
val surfaceDimDark = Color(0xFF191108)
val surfaceBrightDark = Color(0xFF413730)
val surfaceContainerLowestDark = Color(0xFF130B04)
val surfaceContainerLowDark = Color(0xFF221A12)
val surfaceContainerDark = Color(0xFF261E15)
val surfaceContainerHighDark = Color(0xFF31281F)
val surfaceContainerHighestDark = Color(0xFF3C3329)
